### ISSUE TITLE
Velocity Measurements

### ISSUE THREAD

**Issue by ElineHelena** [xerodotc/overdrive-python#2]
Hi! 
Using this API I'm trying to implement an anti collision algorithm on the anki vehicles, which is dependent on the velocity and position measurements. Do you know if these are measured separately (so with different sensors). And it seems that the velocity measurements are only send when a also new location measurements are available, is this correct? There could be over 1 second between location measurements, but for the anti collision algorithm I need higher frequency velocity measurements.. 
Thank you in advance.

**Comment by xerodotc** [comment]
Hi.
From my experience (about 2 years ago),
It's as you said, Anki vehicle only send measurements when it's moving, probably due to how it's were designed and nothing could be done about it (hardware limitation).
The location measurement is not really reliable too, Bluetooth interference could degrade the performance much.

**Comment by ElineHelena** [comment]
Ah that is unfortunate. However, thank you for your quick response.
